package com.technews.javatechnewsapi;

//used to bootstrap and launch a Spring application from a Java main method
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class JavaTechNewsApiApplication {

	//main() function contains an autogenerated function that will spin up the API for us, using the run() method.
	public static void main(String[] args) {
		SpringApplication.run(JavaTechNewsApiApplication.class, args);
	}

}
